# Laboratorio de regresión - 3

## Significancia de factores

|                |                    |
:----------------|--------------------|
| **Nombre**     | André Esteban Vera |
| **Fecha**      | 25/08/2025         |
| **Expediente** | 745232             |

Descarga el archivo de publicidad y carga los datos (Advertising.csv).

In [10]:
# Librerías

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# Leyendo archivo
ADV = pd.read_csv("Advertising.csv")

**¿Hay alguna relación entre el presupuesto para publicidad y las ventas?**

Nuestra primera meta debe ser determinar si hay evidencia en los datos de que haya una asociación entre estas variables.

- ¿Por qué? ¿Qué resultaría si nos diéramos cuenta de la falta de relación entre el presupuesto de publicidad y las ventas?

Para observar si la relación del dinero invertido en las diferentes sectores de publicidad está afectando positivamente nuestras ventas. Y a partir de ello decidir: si no hay relevancia, dejar de invertir en ese sector, y si sí la hay, seguir invirtiendo en ese sector e inclusive invertir aún más.

**¿Qué tan fuerte es esta relación?**
Asumiendo que existe esta relación, ¿nos sirve conocer el impacto que tiene invertir en publicidad en las ventas?

Si, nos sirve bastante, a partir de coonocer su relación con las ventas podemos decidir: si no hay relevancia, dejar de invertir en ese sector, y si sí la hay, seguir invirtiendo en ese sector e inclusive invertir aún más.

**¿Cuáles medios están asociados con las ventas? ¿Qué tan grande es la asociación entre un medio específico y las ventas?**

Hay 3 medios distintos en los datos. ¿Sirve invertir en los 3? ¿Conviene más invertir sólo en uno?

**¿Qué tan seguros estamos de que podríamos predecir ventas futuras?**

**¿La relación es lineal?**

**¿Hay sinergia entre estos medios?**

Puede ser que gastar \\$50,000 en publicidad y otros \\$50,000 en radio es mejor opción que gastar \\$100,000 en televisión. A esto le llamamos efecto de interacción.

Podemos usar regresión lineal para responder todas estas preguntas.

Realiza una regresión lineal:

$$ \text{ventas} \approx \beta_0 + (\beta_1)(\text{TV})$$

## Regresión Lineal con variable TV

In [12]:
X = ADV['TV'].values.reshape([-1,1])

In [13]:
y = ADV['sales'].values.reshape([-1,1])

In [14]:
lr1 = LinearRegression().fit(X, y)

In [15]:
B0 = lr1.intercept_
B0

array([7.03259355])

In [16]:
B1 = lr1.coef_
B1

array([[0.04753664]])

In [17]:
# y estimada y r^2
y_hat1 = lr1.predict(X)
r2 = r2_score(y, y_hat1)
r2

0.611875050850071

### Verificando la precisión de nuestros coeficientes estimados

Recuerda que en el mundo real hay ruidos y errores de medición. Siempre se asume que la verdadera relación entre $X$ y $Y$ es $$Y = \beta_0 + \beta_1 X + \epsilon$$

Se asume que el término de error es independiente de $X$ (el error siempre es el mismo sin importar el valor de $X$). Este modelo describe a la *línea de regresión de la población*, que es la mejor aproximación de la verdadera relación entre $X$ y $Y$. Cuando usamos mínimos cuadrados encontramos la *línea de mínimos cuadrados*.

¿Cuál es la diferencia entre población y muestra?

La población es el conjunto total de lo que nos interesa, y la muestra es un subconjunto de la población : la parte que observamos y medimos para hacer inferencias sonre la población y tomar decisiones.

¿Cuál crees que sea la diferencia entre hacer una regresión con todos los datos de la población y una muestra de ella?

Al hacerlo con la población obtendremos la verdad absoluta sobre nuestros datos, los coeficientes serían tal cual lo que son y nuestras "estimaciones" no serían estimaciones, serían tal cual los resultados reales, mientras que al hacera con la muestra obtendemos solo un acercamiento a la realidad, aqui si serían , con un error de muestreo.

La línea de regresión de la población no se puede observar. El concepto de comparar estas líneas es una extensión natural del acercamiento estadístico estándar de usar información de una muestra para estimar características de una población grande.

Imagina que quieres encontrar la altura promedio de un mexicano $\mu$. Medir a todos y cada uno de los mexicanos en situaciones similares, con la misma regla, mismo operador, y otras incontables formas de minimizar la variación de la medida es una tarea imposible. Lo que podemos asumir es que $\hat{\mu} = \bar{y}$. La media poblacional y la media muestral son diferentes, pero la media muestral es usualmente un buen estimado.

De la misma manera, como no contamos con el 100% de la información para hacer una regresión, los coeficientes $\beta_0$ y $\beta_1$ son desconocidos. Podemos estimarlos usando mínimos cuadrados, encontrando $\hat{\beta_0}$ y $\hat{\beta_1}$. Puede que las muestras que tengamos en ese momento estén un poco por encima de la media, pero otras muestras en otro momento puede que estén debajo de la media. En general, esperamos que el promedio de las aproximaciones $\hat{\mu}$ aproxime a $\mu$.

Esto lleva a la pregunta: ¿qué tan cercanos son nuestros coeficientes estimados a los verdaderos coeficientes? Utilizamos el concepto de error estándar para evaluar esto.

$$ \text{Var}(\hat{\mu})=\text{SE}(\hat{\mu})^2 = \frac{\sigma^2}{n} $$

Donde $\sigma$ es la desviación estándar de cada una de las observaciones $y_i$ de $Y$. El error estándar nos dice la cantidad promedio que el estimado difiere del valor verdadero. Podemos ver en la fórmula que entre más observaciones tengamos el error se hace más pequeño. Las fórmulas para errores estándar de $\hat{\beta_0}$ y $\hat{\beta_1}$ son:

$$ \text{SE}(\hat{\beta_0})^2 = \sigma^2 [\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}]$$

$$ \text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}$$

$$ \sigma^2 = \text{Var}(\epsilon) = \text{RSE}^2 = \frac{\text{RSS}}{n-p}$$

Para que estas fórmulas sean validas asumimos que los errores $\epsilon_i$ tienen varianza común $\sigma^2$ y que no están correlacionados.

Calcula los errores estándar de los coeficientes

In [18]:
n1 = len(y)
x = ADV['TV'].values.astype(float)
res1 = y - y_hat1
rss1 = np.sum(res1**2)
p1 = 2  # parámetros: intercepto y pendiente
rse1 = np.sqrt(rss1 / (n1 - p1))

x_bar1 = x.mean()
Sxx1 = np.sum((x - x_bar1)**2)
se_B0 = np.sqrt(rse1**2 * (1/n1 + (x_bar1**2)/Sxx1))
se_B1 = np.sqrt(rse1**2 / Sxx1)

print(f"RSE = {rse1}")
print(f"SE(beta0) = {se_B0}")
print(f"SE(beta1) = {se_B1}")

RSE = 3.2586563686504624
SE(beta0) = 0.4578429402734785
SE(beta1) = 0.0026906071877968707


Estos errores se pueden usar para calcular intervalos de confianza. Un intervalo de confianza del $95\%$ se define como un rango de valores en el cuál se encuentra el desconocido valor verdadero con un $95\%$ de probabilidad.

Otra forma de verlo es que si tomamos muestras repetidas y construimos un intervalo de confianza para cada una, el $95\%$ de los intervalos creados van a contener el valor verdadero. Para la regresión el intervalo de confianza del $95\%$ toma la forma:

$$ \hat{\beta_j} \pm 2\text{SE}(\hat{\beta_j})$$

Calcula los intervalos de confianza para los coeficientes estimados:

In [19]:
intervaloB0 = (B0 - 2*se_B0, B0 + 2*se_B0)
intervaloB1 = (B1 - 2*se_B1, B1 + 2*se_B1)

print(f"IC beta0: ({intervaloB0[0], intervaloB0[1]}")
print(f"IC beta1: ({intervaloB1[0], intervaloB1[1]}")

IC beta0: ((array([6.11690767]), array([7.94827943]))
IC beta1: ((array([[0.04215543]]), array([[0.05291785]]))


Los errores estándar también se usan para realizar pruebas de hipótesis. La prueba de hipótesis más común es probar la hipótesis nula de:

$$ H_0: \text{No hay relación entre } X \text{ y } Y \ \ \ \ (\beta_1=0)$$

contra la hipótesis alternativa:
$$ H_0: \text{Hay alguna relación entre } X \text{ y } Y \ \ \ (\beta_1 \neq 0)$$

Explica con tus palabras el significado de la hipótesis nula y la hipótesis alternativa.

**La Hipótesis Nula** es la postura “por defecto”: no pasa nada, no hay efecto, no hay relación, en regresión simple significa que no hay relación lineal entre las dos variables y en regresión múltiple significa que la variable aprueba no es significante a comparación de las otras.

**La Hipótesis Alterna** afirma que si está pasando algo, osea que si hay efecto/relación. En regresión simple: que si hay relación lineal; y en la múltiple significa que la variable aprueba si es significante a comparación de las otras.

Para probal la hipótesis nula debemos determinar si nuestro estimado $\hat{\beta_1}$ de $\beta_1$ está lo suficientemente alejado de cero para que podamos decir con confianza que este valor no es cero. 

¿Qué tan lejos? Depende de qué tanta confianza tengamos en el estimado encontrado. Si nuestro error estándar es pequeño y nuestro estimado está alejado de cero podríamos decir que hay muy poca probabilidad de que el valor verdadero sea 0. En cambio, si nuestro error estándar es grande y nuestro estimado está muy cerca de cero, entonces podrías ser que el valor verdadero sea cero y que no haya relación entre las variables.

Se calcula un *estadístico t* dado por
$$ t = \frac{\hat{\beta_j} - \mu}{\text{SE}(\hat{\beta_j})} $$

donde $\mu$ es el valor contra el que queremos probar.

Calcula el estadístico t para tus coeficientes estimados, usando como referencia la prueba de hipótesis.

In [20]:
t_B0 = B0 / se_B0
t_B1 = B1 / se_B1

print(f"t_B0 ={t_B0}")
print(f"t_B1 ={t_B1}")

t_B0 =[15.36027517]
t_B1 =[[17.6676256]]


La distribución t tiene forma de campana y se parece bastante a la distribución normal cuando $n > 30$. Ya sólo es cuestión de calcular la probabilidad de observar cualquier número tal que su valor absoluto sea igual o mayor que el valor absoluto del estadístico t calculado. En otras palabras:
$$ P(|x| \geq |t|) $$

A esta probabilidad la llamamos *p-value*. Un *p-value* pequeño indica que es poco probable que exista por puro azar una relación significativa entre predictor y respuesta, en caso de que no haya una asociación real entre predictor y respuesta. En otras palabras, el *p-value* te dice la probabilidad de que parezca que hay relación cuando no la hay.

Si el *p-value* es pequeño, inferimos que sí hay una asociación entre el predictor y la respuesta, y **rechazamos la hipótesis nula**.
  

¿Qué tan pequeño? Depende de la aplicación. Un valor muy común es del $5\%$.

Utiliza el siguiente código para calcular el *p-value* para tus coeficientes

`from scipy import stats`

`p_bj = 2*(1 - stats.t.cdf(np.abs(t_bj), n-p))`

In [21]:
from scipy import stats

df = n1 - 2
p_B0 = 2*(1 - stats.t.cdf(np.abs(t_B0), df))
p_B1 = 2*(1 - stats.t.cdf(np.abs(t_B1), df))

print(f"p_B0 ={p_B0}")
print(f"p_B1 ={p_B1}")

p_B0 =[0.]
p_B1 =[[0.]]


¿Se rechaza la hipótesis nula? ¿Qué significa?

Que si pasó algo, osea que si hay relación lineal.

Realiza otras dos regresiones. Ya tienes hecha la regresión de ventas dado el gasto en publicidad de TV. Realiza la regresión para gastos en radio y gastos en periódico. Organiza las respuestas para que debajo de esta celda se tenga:
- Título de regresión
- Coeficientes estimados
- Errores estándar de los coeficientes
- Intervalos de confianza
- Estadísticos t
- p-values
- Observaciones

## Regresión Lineal con variable Newspaper

In [22]:
# Regresión lineal con variable Newspaper
X2 = ADV['newspaper'].values.reshape([-1,1])
y2 = ADV['sales'].values.reshape([-1,1])
lr2 = LinearRegression().fit(X2, y2)
lr2

LinearRegression()

In [23]:
# B0 (intercepto)
B0_2 = lr2.intercept_
B0_2


array([12.35140707])

In [24]:
# B1 (coeficiente newspaper)
B1_2 = lr2.coef_
B1_2

array([[0.0546931]])

In [25]:
# y estimada y r^2
y_hat2 = lr2.predict(X2)
r2_2 = r2_score(y2, y_hat2)
r2_2

0.05212044544430516

In [26]:
# errores estandar de los coeficientes
n2 = len(y2)
x2 = ADV['newspaper'].values.astype(float)
res2 = y2 - y_hat2
rss2_2 = np.sum(res2**2)
p2 = 2  # parámetros: intercepto y pendiente
rse2 = np.sqrt(rss2_2 / (n2 - p2))

x_bar2 = x2.mean()
Sxx2 = np.sum((x2 - x_bar2)**2)
se_B0_2 = np.sqrt(rse2**2 * (1/n2 + (x_bar2**2)/Sxx2))
se_B1_2 = np.sqrt(rse2**2 / Sxx2)

print(f"RSE = {rse2}")
print(f"SE(beta0) = {se_B0_2}")
print(f"SE(beta1) = {se_B1_2}")

RSE = 5.092480366520192
SE(beta0) = 0.6214201876094345
SE(beta1) = 0.01657572187635816


In [27]:
# intervalos de confianza para los coeficientes
intervaloB0_2 = (B0_2 - 2*se_B0_2, B0_2 + 2*se_B0_2)
intervaloB1_2 = (B1_2 - 2*se_B1_2, B1_2 + 2*se_B1_2)

print(f"IC beta0: ({intervaloB0_2[0], intervaloB0_2[1]}")
print(f"IC beta1: ({intervaloB1_2[0], intervaloB1_2[1]}")

IC beta0: ((array([11.10856669]), array([13.59424744]))
IC beta1: ((array([[0.02154165]]), array([[0.08784454]]))


In [28]:
# t estadistico 
t_B0_2 = B0_2 / se_B0_2
t_B1_2 = B1_2 / se_B1_2

print(f"t_B0_2 ={t_B0_2}")
print(f"t_B1_2 ={t_B1_2}")

t_B0_2 =[19.87609562]
t_B1_2 =[[3.29959074]]


In [29]:
# p values
from scipy import stats

df2 = n2 - 2
p_B0_2 = 2*(1 - stats.t.cdf(np.abs(t_B0_2), df))
p_B1_2 = 2*(1 - stats.t.cdf(np.abs(t_B1_2), df))

print(f"p_B0_2 ={p_B0_2}")
print(f"p_B1_2 ={p_B1_2}")

p_B0_2 =[0.]
p_B1_2 =[[0.0011482]]


**OBSERVACIONES**

El newspaper puede tener una relación significativa con las ventas, ya que su p-value es muy cercano a 0.


## Regresión Lineal con variable Radio

In [30]:
# Regresión lineal con variable Radio
X3 = ADV['radio'].values.reshape([-1,1])
y3 = ADV['sales'].values.reshape([-1,1])
lr3 = LinearRegression().fit(X3, y3)
lr3

LinearRegression()

In [31]:
# B0 (intercepto)
B0_3 = lr3.intercept_
B0_3

array([9.3116381])

In [32]:
# B1 (coeficiente newspaper)
B1_3 = lr3.coef_
B1_3

array([[0.20249578]])

In [33]:
# y estimada y r^2
y_hat3 = lr3.predict(X3)
r2_3 = r2_score(y3, y_hat3)
r2_3

0.33203245544529525

In [34]:
# errores estandar de los coeficientes
n3 = len(y3)
x3 = ADV['radio'].values.astype(float)
res3 = y3 - y_hat3
rss2_3 = np.sum(res3**2)
p3 = 2  # parámetros: intercepto y pendiente
rse3 = np.sqrt(rss2_3 / (n3 - p3))

x_bar3 = x3.mean()
Sxx3 = np.sum((x3 - x_bar3)**2)
se_B0_3 = np.sqrt(rse3**2 * (1/n3 + (x_bar3**2)/Sxx3))
se_B1_3 = np.sqrt(rse3**2 / Sxx3)

print(f"RSE = {rse3}")
print(f"SE(beta0) = {se_B0_3}")
print(f"SE(beta1) = {se_B1_3}")

RSE = 4.27494435490106
SE(beta0) = 0.5629004962718711
SE(beta1) = 0.020411306360090635


In [35]:
# intervalos de confianza para los coeficientes
intervaloB0_3 = (B0_3 - 2*se_B0_3, B0_3 + 2*se_B0_3)
intervaloB1_3 = (B1_3 - 2*se_B1_3, B1_3 + 2*se_B1_3)

print(f"IC beta0: ({intervaloB0_3[0], intervaloB0_3[1]}")
print(f"IC beta1: ({intervaloB1_3[0], intervaloB1_3[1]}")

IC beta0: ((array([8.1858371]), array([10.43743909]))
IC beta1: ((array([[0.16167317]]), array([[0.2433184]]))


In [36]:
# t estadistico 
t_B0_3 = B0_3 / se_B0_3
t_B1_3 = B1_3 / se_B1_3

print(f"t_B0_3 ={t_B0_3}")
print(f"t_B1_3 ={t_B1_3}")

t_B0_3 =[16.54224531]
t_B1_3 =[[9.92076547]]


In [37]:
# p values
from scipy import stats

df3 = n3 - 2
p_B0_3 = 2*(1 - stats.t.cdf(np.abs(t_B0_3), df))
p_B1_3 = 2*(1 - stats.t.cdf(np.abs(t_B1_3), df))

print(f"p_B0_3 ={p_B0_3}")
print(f"p_B1_3 ={p_B1_3}")

p_B0_3 =[0.]
p_B1_3 =[[0.]]


**OBSERVACIONES**

La radio debe tener una relación significativa con las ventas, ya que su p-value es 0.


## Regresión lineal múltiple

En lugar de hacer una regresión para cada factor independiente, quizás se puede extender el modelo para que tenga varios factores dentro:

$$ Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p + \epsilon $$

Para nuestro ejemplo de publicidad:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

Utiliza la librería `statsmodels` para realizar la regresión. Por defecto la librería statsmodels no toma en cuenta el intercepto ($\beta_0$), por lo que se tendrá que agregar una columna de unos de tamaño *n* a la matriz X.

`import statsmodels.api as sm`

`ols = sm.OLS(Y, X)`

`results = ols.fit()`

`results.summary()`

In [38]:
import statsmodels.api as sm

# X = [1, TV, radio, newspaper]
unos1 = np.ones([n1,1])
x_tv = ADV['TV'].values.reshape(-1,1)
x_radio = ADV['radio'].values.reshape(-1,1)
x_newspaper = ADV['newspaper'].values.reshape(-1,1)
X = np.hstack([unos1, x_tv, x_radio, x_newspaper])

y = ADV['sales'].values
ols1 = sm.OLS(y,X)
results1 = ols1.fit()
results1.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Fri, 29 Aug 2025   Prob (F-statistic):           1.58e-96
Time:                        14:18:52   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
x1             0.0458      0.001     32.809      0.000       0.043       0.049
x2             0.1885      0.009     21.893      0.000       0.172       0.206
x3            -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

¿Qué diferencias puedes observar entre los *p-values* de una regresión múltiple y los encontrados en las regresiones simples? ¿Por qué crees que existen estas diferencias?

Al analizar la variable "newspaper" por separado, su p-value es muy cercano a 0, por lo que creeriamos que si es relevante su relación con las ventas, pero al analizar las vairables juntas en la regresión múltiple su p-value da 0.86, lo que indica que su relación con las ventas no es de importancia. 
Yo creo que estas diferencias existen porque al analizar una variable por si sola se "enmascara" ya que es la única variable que tenemos en la información. Al analizarla junto a las otrs variables sale ahora si la relación verdadera. 

In [39]:
# multiplicamos las variables TV y radio en lugar de newspaper
# X = [1, TV, radio, tv*radio]

unos1 = np.ones([n1,1])
x_tv = ADV['TV'].values.reshape(-1,1)
x_radio = ADV['radio'].values.reshape(-1,1)
x_tv_radio = x_tv * x_radio
X = np.hstack([unos1, x_tv, x_radio, x_tv_radio])

y = ADV['sales'].values
ols2 = sm.OLS(y,X)
results2 = ols2.fit()
results2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.968
Model:                            OLS   Adj. R-squared:                  0.967
Method:                 Least Squares   F-statistic:                     1963.
Date:                Fri, 29 Aug 2025   Prob (F-statistic):          6.68e-146
Time:                        14:18:52   Log-Likelihood:                -270.14
No. Observations:                 200   AIC:                             548.3
Df Residuals:                     196   BIC:                             561.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.7502      0.248     27.233      0.000       6.261       7.239
x1             0.0191      0.002     12.699      0.000       0.016       0.022
x2             0.0289      0.009      3.241      0.001       0.011       0.046
x3             0.0011   5.24e-05     20.727      0.000       0.001       0.001
==============================================================================
Omnibus:                      128.132   Durbin-Watson:                   2.224
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1183.719
Skew:                          -2.323   Prob(JB):                    9.09e-258
Kurtosis:                      13.975   Cond. No.                     1.80e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.8e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [40]:
# X = [1, TV, radio, newspaper, ,tv*radio, tv*newspaper, radio*newspaper]
unos1 = np.ones([n1,1])
x_tv = ADV['TV'].values.reshape(-1,1)
x_radio = ADV['radio'].values.reshape(-1,1)
x_newspaper = ADV['newspaper'].values.reshape(-1,1)
x_tv_radio = x_tv * x_radio
x_tv_np = x_tv * x_newspaper
x_radio_np = x_radio * x_newspaper


X = np.hstack([unos1, x_tv, x_radio, x_newspaper, x_tv_radio, x_tv_np, x_radio_np ])

y = ADV['sales'].values
ols2 = sm.OLS(y,X)
results3 = ols2.fit()
results3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     993.3
Date:                Fri, 29 Aug 2025   Prob (F-statistic):          3.68e-142
Time:                        14:18:52   Log-Likelihood:                -267.49
No. Observations:                 200   AIC:                             549.0
Df Residuals:                     193   BIC:                             572.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.4602      0.318     20.342      0.000       5.834       7.087
x1             0.0203      0.002     12.633      0.000       0.017       0.024
x2             0.0229      0.011      2.009      0.046       0.000       0.045
x3             0.0170      0.010      1.691      0.092      -0.003       0.037
x4             0.0011   5.72e-05     19.930      0.000       0.001       0.001
x5         -7.971e-05   3.58e-05     -2.227      0.027      -0.000   -9.12e-06
x6            -0.0001      0.000     -0.464      0.643      -0.001       0.000
==============================================================================
Omnibus:                      111.385   Durbin-Watson:                   2.222
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              767.483
Skew:                          -2.046   Prob(JB):                    2.20e-167
Kurtosis:                      11.681   Cond. No.                     3.80e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.8e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Referencia

James, G., Witten, D., Hastie, T., Tibshirani, R.,, Taylor, J. (2023). An Introduction to Statistical Learning with Applications in Python. Cham: Springer. ISBN: 978-3-031-38746-3

## Addendum

Para calcular los *p-values* de los parámetros sin `statsmodels`:
1. Calcular RSS
2. Calcular RSE
3. `var_beta = np.linalg.inv(X.T @ X) * rse**2` (X con columna de intercepto)
4. `std_beta = np.sqrt(var_beta.diagonal())` El orden de los valores corresponde al orden de los factores en las columnas de la matriz $X$.
5. Calcular *estadístico t*
6. Calcular *p-value*